### ISSUE TITLE
Blendshape optimizer incompatible with other things that use mesh baking

### ISSUE THREAD

**Issue by fluffy-critter** [VRCFury/VRCFury#107]
I've been trying to use [ValueFactory's goo shader](https://goo.shader.gay/), which requires a mesh baking step that replaces the mesh on the Skinned Mesh Renderer. It creates an additional mesh with some added attribute data that the Skinned Mesh Renderer is directed to use instead.

When using VRCFury's blendshape optimizer, however, the shader fails to work right, and one of the shader's checks raises a warning that the mesh hadn't been baked. I'm guessing that either the optimizer is optimizing the original mesh from the prefab (rather than the one actually referenced by the renderer), or that it's stripping the added attribute data out of the mesh data.

For now as a workaround I've disabled the blendshape optimizer (which doesn't really make that big a difference on my avatar anyway), but it'd be nice to figure out what's causing the conflict and how to avoid it in the future.

**Comment by SenkyDragon** [comment]
The VF goo shader baker determines if it's already been baked by looking at the filename. If it doesn't end in their magic string, it assumes it hasn't been baked yet. It's pretty fragile, and I've been reluctant to special case the filename that vrcfury generates just to make this one thing happy.

**Comment by fluffy-critter** [comment]
Ah, okay, that makes sense. Disabling the blendshape optimizer had disabled the warning but I haven't actually tested in-game to see if the required mesh attributes are present, and Value mentioned another thing that might be going on with Unity's build-time optimization that might be the actual culprit for things not working.

Do you have recommendations for a better way to detect whether a mesh is already baked than by looking at the filename? I don't know of any other shaders which bake a mesh in this way (all the others I can think of use sideband data such as SDF textures) so I don't know how others have solved this issue.

Thanks!

**Comment by valuef** [comment]
`AssetDatabase.SetLabels` and `AssetDatabase.GetLabels` seems like it would be a better way of doing this, but the label information seems to be discarded after VRCFury creates its own copy of the mesh in the Temp Packages folder it uses :/

**Comment by valuef** [comment]
> `AssetDatabase.SetLabels` and `AssetDatabase.GetLabels` seems like it would be a better way of doing this, but the label information seems to be discarded after VRCFury creates its own copy of the mesh post blendshape optimization in the Temp Packages folder it uses :/

```diff
index 4c43a8e..42c0e4f 100644
--- a/Packages/com.vrcfury.vrcfury/Editor/VF/Builder/MutableManager.cs
+++ b/Packages/com.vrcfury.vrcfury/Editor/VF/Builder/MutableManager.cs
@@ -307,6 +307,10 @@ namespace VF.Builder {
             var copy = SafeInstantiate(original);
             copy.name = original.name;
             VRCFuryAssetDatabase.SaveAsset(copy, tmpDir, $"{copy.name} for {owner.name}");
+
+            var labels = AssetDatabase.GetLabels(original);
+            AssetDatabase.SetLabels(copy, labels);
+
             mutableOwners[copy] = owner;
             originalToMutable[(original, owner)] = copy;
             return copy;
```
This'll make the mesh retain the label data. Unity doesn't want to show the label in the inspector still unless you move the mesh out of the Packages folder.

I'm completely uninformed on whether or not this is the best place to put the label copying code or if it's something you want in VRCFury in the first place, but seems like this would be a good solution to the name issue. Please let me know 👍

**Comment by SenkyDragon** [comment]
Labels make a lot of sense. I didn't know those existed, they seem pretty infrequently used. Yes, we should definitely keep them while cloning.

**Comment by SenkyDragon** [comment]
Not pretty, but you could add a vertex with a magic position into the baked file, then check if it's there to decide if it's been baked or not ;)

**Comment by SenkyDragon** [comment]
Closing this, since I believe @valuef found a solution. Please re-open if something else needs done.
