### ISSUE TITLE
[Feature Requests] Add VRCFury on VCC (CreatorCompanion)?

### ISSUE THREAD

**Issue by AndreasFromDanmark** [VRCFury/VRCFury#11]
Is there a way to do this??

![Skærmbillede 2023-05-10 152448](https://github.com/VRCFury/VRCFury/assets/35656492/988555ff-9029-42fa-8f37-858daf02e5d0)

**Comment by SenkyDragon** [comment]
There are instructions for this at the bottom of the readme.
