### ISSUE TITLE
DirectTreeOptimiser will incorrectly optimise layers targeted by a VRC Animator Layer Control behaviour

### ISSUE THREAD

**Issue by TheLastRar** [VRCFury/VRCFury#111]
Take the following example animator;

A two state layer with an on and off state setting layer 1's weight to 0 or 1 respectively for layer 0
![image](https://github.com/VRCFury/VRCFury/assets/4604733/72b488c0-4b7b-4491-b493-a4965b75a992)

A single state layer for layer 1
![image](https://github.com/VRCFury/VRCFury/assets/4604733/c6ebdaf2-1feb-4c7a-a1d3-d43f0de39ed1)

The direct tree optimiser will optimise layer 1, and the Animator Layer Control behaviours in layer 0 are removed
![image](https://github.com/VRCFury/VRCFury/assets/4604733/88348c99-6446-4e78-bed1-a0e52168e83f)
 
This results in the animation in layer 1 always playing, rather then being toggled by layer 0

**Comment by SenkyDragon** [comment]
I'm surprised anyone has ever done this, rather than just sharing the conditions. Although I guess I shouldn't be surprised 😅

**Comment by TheLastRar** [comment]
Discovered it when merging in the sub animators used in https://booth.pm/en/items/3230003 (as VRCF doesn't process them otherwise).

That didn't work for other reasons (and gave up trying make a VRCF prefab of it), but I figured I'd report this issue in case someone else runs into it.
