### ISSUE TITLE
Gesture blink overrides not working

### ISSUE THREAD

**Issue by fluffy-critter** [VRCFury/VRCFury#120]
I recently switched to using VRCFury's gesture controller (from a traditionally-authored one), and the blink overrides are not working for me.

<img width="454" alt="image" src="https://github.com/VRCFury/VRCFury/assets/347162/cc470cb0-a160-431f-9ed3-7908b7fed33c">

In this setup, I have blink overrides se for the left-hand victory and fingerpoint gestures, but while I am making those gestures, blinks are still occurring.

I'm running VRCFury 1.425.0 on VRC SDK 3.3.0.

**Comment by SenkyDragon** [comment]
I somehow missed this issue, but assuming you were using VRC's built-in blink mechanic, this issue should now be resolved. Previously, this "disable blink" feature only worked with VRCFury's built-in blink controller, but now it works with vrchat's default one as well.
