### ISSUE TITLE
Suggestion: Platform specific toggle actions

### ISSUE THREAD

**Issue by Different-Name** [VRCFury/VRCFury#129]
Platform specific toggle actions would make a clean way to allow the removal of meshes from quest avatars without syncronisation issues.
Currently to remote a clothing item from a quest avatar and have it still be clothed when the PC avatar is clothed, a duplicate mesh needs to be created for quest and then that must be added to all the toggles, the pc mesh is then force object state deleted from the quest avatar and visa versa for the pc avatar.
This feature would allow for using the same game object

**Comment by SenkyDragon** [comment]
Fixed in e7cfde83
