### ISSUE TITLE
Toggles with wheel slider is always generating menu

### ISSUE THREAD

**Issue by jerryzmtz** [VRCFury/VRCFury#133]
If you do not assign any path in Menu path, no menu will be generated for a single toggle. However, if you are using wheel slider, a menu will always be generated even if you have not assigned anyone. 
![Toggle_WithoutSlider](https://github.com/VRCFury/VRCFury/assets/26083118/655ae85e-ff6c-4d58-8d9a-fa10bd8989da)
![Toggle_WithoutSlider_Menu](https://github.com/VRCFury/VRCFury/assets/26083118/29e648fc-bc8e-458f-a0d2-591074393b1f)
![Toggle_WithSlider](https://github.com/VRCFury/VRCFury/assets/26083118/2bff473b-ec8c-4446-b9e7-2d342d079449)
![Toggle_WithSlider_Menu](https://github.com/VRCFury/VRCFury/assets/26083118/a6f9b56d-3f9c-43cc-89c9-56c344ddf1ea)

**Comment by jerryzmtz** [comment]
I am on VRCF 1.451.0

**Comment by GameGeek720** [comment]
Should now be fixed
