### ISSUE TITLE
BlendShapeLink: Fuzzy matching fails with blendshapes named in Japanese

### ISSUE THREAD

**Issue by TheLastRar** [VRCFury/VRCFury#136]
See attached image

The mesh being linked only has a small subset of the shape keys that the base mesh has.

![image](https://github.com/VRCFury/VRCFury/assets/4604733/eafadb4d-6f04-4ccf-b75a-7db96a145e00)

**Comment by SenkyDragon** [comment]
I think this was fixed a while ago.
