### ISSUE TITLE
[Feature Request] Add Invert Toggle Animation to Toggle

### ISSUE THREAD

**Issue by Toys0125** [VRCFury/VRCFury#14]
The issue is that an already active prop I want on by default causes the toggle when enabling to deactivate the prop. I can fix it by having it auto-deactivate using the force object state, but the issue is that forces people have to have animations on to see it active,
Could it be possible to have either an invert or have default state for the toggle prop?

**Comment by SenkyDragon** [comment]
Use force object state to force it off, then use Default On AND Show in Rest Pose options on the toggle, which will make it visible without your animations enabled.

**Comment by SenkyDragon** [comment]
This complexity will likely be simplified in the future. I believe the plan is to make it so that:

1. Object Toggle will add an implicit Force Object State Disabled by default (since that's usually what people want it to do anyways)
2. Default On should probably be linked to Show in Rest Pose, since I'm not sure why you would want one and not the other.

**Comment by Toys0125** [comment]
> Use force object state to force it off, then use Default On AND Show in Rest Pose options on the toggle, which will make it visible without your animations shown.

I forgot about shown in rest pose. Thanks for clarifying.


> This complexity will likely be simplified in the future. I believe the plan is to make it so that:
> 
> 1. Object Toggle will add an implicit Force Object State Disabled by default (since that's usually what people want it to do anyways)
> 2. Default On should probably be linked to Show in Rest Pose, since I'm not sure why you would want one and not the other.

Want to make sure still have the option to use the force object state to allow to disable things when parameter is active to allow complex control.

**Comment by SenkyDragon** [comment]
I've split this issue into #22 and #23
