### ISSUE TITLE
[Feature Request] Auto-detect Same toggles

### ISSUE THREAD

**Issue by Toys0125** [VRCFury/VRCFury#15]
I have a toggle set in multiple clothes in the same location, and it just duplicates the menu toggle.
![Unity_2023-05-17_22-30-57](https://github.com/VRCFury/VRCFury/assets/15334903/3b9e2f16-2e5c-4596-81df-36daf316bc6d)
![Unity_2023-05-17_22-33-58](https://github.com/VRCFury/VRCFury/assets/15334903/b0c0f89d-8020-4a80-ac93-5e137f7e1ce6)

**Comment by SenkyDragon** [comment]
Typically toggles are shipped with the package that they control. Is there a reason this toggle is shipped with the clothes rather than with the base model that presumably they are affecting?

**Comment by SenkyDragon** [comment]
I'm going to close this for now. If you have any more information, please feel free to leave another comment or discuss in the discord.

**Comment by Happyrobot33** [comment]
I think this should be re-opened, as I am running into this issue myself. This also occurs if you have a Full Controller feature that adds menus at the same destination. I think it should untimately either be a option to compress them or should just automatically compress them as it doesnt make sense usually to have multiple of the same menu input

@SenkyDragon
