### ISSUE TITLE
Material animations for all meshes

### ISSUE THREAD

**Issue by babo4d** [VRCFury/VRCFury#152]
These features are implemented (destructively) in https://github.com/ImLeXz/LexiTools

> [Generate Material Anims](https://github.com/ImLeXz/LexiTools#generate-material-anims)
> Automatically creates an animation that animates a given shader property for a specified shader on every mesh and every material under the root object
>
> [SetMaterialProps](https://github.com/ImLeXz/LexiTools#setmaterialprops)
> Automatically sets a given shader property for a specified shader on every mesh and every material under the root object. Allows for floats, ints, colors and textures to be adjusted.

It would be useful for non-destructive edits and prefabs, for example:
- Toggle effects like outlines, rim lighting, emissions
- Adjust/animate lighting properties like monochromatic and min brightness

**Comment by SenkyDragon** [comment]
Doesn't this already exist? Have you tried the vrcfury `Material Property` action within a toggle? :)

**Comment by babo4d** [comment]
Very nice! I did not think to look there.

So this covers setting material properties, aside from implementation details -- the original materials are still included even if I don't need them.

For animated properties this requires an animation clip, so it can't apply to "all meshes" like the simple toggles.

**Comment by babo4d** [comment]
> So this covers toggling material properties, aside from implementation details -- the original materials are always included even if I don't need them.

I see this is already addressed by the new "Apply During Upload" component. Thanks.

**Comment by SenkyDragon** [comment]
I think I missed something. Is there still something left to do in this ticket that isn't implemented already?

**Comment by SenkyDragon** [comment]
Please reopen if there it still something that needs done for this ticket.
