### ISSUE TITLE
Proxy animations means layer is not merged into controller

### ISSUE THREAD

**Issue by imagitama** [VRCFury/VRCFury#160]
As discussed in Discord: https://discord.com/channels/1001423276553285653/1001424777401077830/1173192109646413835

# Issue

If you use any proxy animations in your controller (such as a default one from the SDK like `Packages/com.vrchat.avatars/Samples/AV3 Demo Assets/Animation/Controllers/vrc_AvatarV3HandsLayer.controller`) VRCFury will completely ignore the layer.

If you replace the proxy animation with anything else, it includes it.

# Reproduction

1. Add VRCFury (1.531) component and add Full Controller
2. Select `vrc_AvatarV3HandsLayer.controller` and target FX
3. Build/play and it logs something like

```
Removing layer [VF49] Left Hand from FX because it doesn't do anything
```

Replacing a random proxy animation with _any_ other animation means it includes the layer.

# Why is this important

Sometimes you need to manually specify the hand/finger animations. I will usually copy the demo `vrc_AvatarV3HandsLayer.controller` as I don't need any custom hand animations. Instead of manually copying the layers I want to use VRCFury to automatically add them in.

**Comment by SenkyDragon** [comment]
Not a bug. Merging humanoid muscle animations into FX has never been supported, because vrchat's default FX mask excludes muscles. For hand gestures, merge it into gesture instead.
