### ISSUE TITLE
Slider Toggles are not functional in local states.

### ISSUE THREAD

**Issue by DJFPaul** [VRCFury/VRCFury#162]
Toggles utilizing sliders work fine when using a a normal synced parameter.
However, using a local state does not work with sliders.

I have tested this with both Blendshapes and Animations for either state.

Additionally tried adding a dummy remote state which also did not make it work.
The remote state will correctly follow the slider, while the local one will not change anything.

This works:
![working](https://github.com/VRCFury/VRCFury/assets/35642602/6275e6e4-8782-43f5-9ffe-bb4832f857f2)

This does not work:
![notworking](https://github.com/VRCFury/VRCFury/assets/35642602/59cf9127-0928-4450-9417-e509569e884c)

**Comment by SenkyDragon** [comment]
Resolved in df69953b54589601278a962e2be88f3de1724d57
