### ISSUE TITLE
support for headless building

### ISSUE THREAD

**Issue by LmonUnluck** [VRCFury/VRCFury#167]
Im unable to build asset bundles (avatars) while using unity's "-batchmode" due to the fact its unable to locate the main window

I am aware that this may be intended by design but i have a working local patch to work with my asset bundler

An easy solution is to add to "GetEditorMainWindowPos"
```
string[] args = System.Environment.GetCommandLineArgs();
for (int i = 0; i < args.Length; i++)
{
    if (args[i] == "-batchmode")
    {
        return Rect.zero;
    }
}
```

If you would like to have more information regarding the use case feel free to ask

**Comment by SenkyDragon** [comment]
Is that the only blocker? I'm surprised it doesn't blow up trying to do things like creating the popover dialog.

**Comment by LmonUnluck** [comment]
> Is that the only blocker? I'm surprised it doesn't blow up trying to do things like creating the popover dialog.

yeah surprisingly, i thought there would've been more to it but ive yet to have a proper issue with it running in headless mode

**Comment by SenkyDragon** [comment]
I am a bit curious of your use case though ;)

**Comment by LmonUnluck** [comment]
> I am a bit curious of your use case though ;)

Im currently running an uploading service that builds avatars ahead of time to keep uploading down to less than a minute regardless of where you are located (I suffer from Australian internet so my uploads sometimes take 10+ minutes)

I have some general information on my website https://uploader.lmon.au/

If you are wanting a demo of the application feel free to add me on discord @lmon and I can flick you a code to use with the app
