### ISSUE TITLE
how does the Menu+Paths Prefix work

### ISSUE THREAD

**Issue by Melodycloudu** [VRCFury/VRCFury#169]
Can I have a indepth explanation and what I can do or cant do with this feature as im trying to add a menu to a menu that isnt the root menu and your documentation and info text with this feature doesnt actually explain how this works or how to use it correctly. so I can have it not dump the new menu into my root avatar menu

**Comment by SenkyDragon** [comment]
Please ask for support on the discord at https://vrcfury.com/discord . This issue system is for reported bugs and feature requests only.
