### ISSUE TITLE
Issue with Gogo Loco Broke Vrcfury prefab

### ISSUE THREAD

**Issue by hamhamfreak** [VRCFury/VRCFury#17]
Ok so my understanding The broke version prefab doesnt have fly as stated in the documentation BUT for some reason it has goBeyond Prefab in the Broke prefab there for it has fly when it shouldnt  
![image](https://github.com/VRCFury/VRCFury/assets/9193367/96925626-c859-4aff-bcd4-8934b1182912)

**Comment by SenkyDragon** [comment]
Broke does have fly. The docs say that Broke is Beyond, plus more stuff.

**Comment by hamhamfreak** [comment]
Well which 9ne doesn't contain gly but all the other stuff for quest use

**Comment by SenkyDragon** [comment]
That's gogoloco all.
