### ISSUE TITLE
Hand gestures override animations in action layer

### ISSUE THREAD

**Issue by AtriusX** [VRCFury/VRCFury#172]
I noticed this happening a few days ago, but I wanted to take a bit of time to dig into this just in case a recent change to my avatar potentially broke something. Currently, it appears that VRC Fury is moving the left & right hand gesture layers into the FX controller, which is breaking hand motion in animations that have them in the action controller.

For the time being, I've found that I'm able to alleviate the issue by just setting the gesture layer to use the default gesture controller. This workaround likely won't work for others who have custom hand gesture animations in that controller, though.

**Comment by SenkyDragon** [comment]
This was fixed at some point.
