### ISSUE TITLE
Avatar upload getting Avatar Validation Failed

### ISSUE THREAD

**Issue by Anubis06211** [VRCFury/VRCFury#181]
Utilize VRC fury to create avatar toggles and menu. I have experienced several times where upon upload I receive avatar validation failed when uploading. Cannot find cause. When VRCFury is removed the avatar uploads. Please let me know what I can provide to assist in this.

**Comment by SenkyDragon** [comment]
Please post on the discord for support requests that are not verified bugs. https://vrcfury.com/discord
