### ISSUE TITLE
Keep version synced into package.json

### ISSUE THREAD

**Issue by favoyang** [VRCFury/VRCFury#2]
Hi there,

The project is well organized but didn't sync the version into package.json. The only place to track versions seems to be Git tags. But all versions remain `0.0.0`. It prevents using tools like [OpenUPM](https://openupm.com/packages/com.vrcfury.vrcfury/) to track the changes.

There're many ways to automate the version control process, either using a homemade script or even better, using a semantic version to automate it ([refs](https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c)).

**Comment by SenkyDragon** [comment]
Not sure how I missed this issue, but this problem is known. It's definitely on the to-fix list.
