### ISSUE TITLE
SpsPatcher doesn't patch #include_with_pragmas

### ISSUE THREAD

**Issue by bigibas123** [VRCFury/VRCFury#202]
When patching a shader for SPS VRCFury doesn't replace the path after `#include_with_pragmas` with one that works from the new position. This results in shader compilation failing when using the new directive making the mesh turn pink.
![image](https://github.com/VRCFury/VRCFury/assets/6242563/7a5568fe-6f07-4c3d-9789-660b7a54e444)

A current workaround is using the full path to the included file but this isn't ideal for portability.

Patch wise it can be treated the same as a normal include, where it prefixes the path with `fullPathToOriginalShaderfile\..\`

**Comment by SenkyDragon** [comment]
Got a shader that is affected by this?

**Comment by bigibas123** [comment]
> Got a shader that is affected by this?

I've split off my main repo to [https://github.com/bigibas123/bigishader](https://github.com/bigibas123/bigishader).

The shader that's giving me trouble is the [BigiAudioLink_frag.shader](https://github.com/bigibas123/bigishader/blob/main/BigiAudioLink_frag.shader) (`Bigi/AudioLink_frag` in editor)

It'll give a warning about missing a custom editor but it doesn't need it to reproduce the bug.

**Comment by bigibas123** [comment]
Thank you!
