### ISSUE TITLE
[QoL] Foldable VRCFury components

### ISSUE THREAD

**Issue by meriler98** [VRCFury/VRCFury#214]
So when I work with toggles I usually put a handful of them and they sometimes clutter a good portion of screen. May there be a button to fold those options so they don't cover a huge portion?
Few points to take:
- Save fold value of items so when you reselect them they not come all unfolded, but instead only those you were working with and save those which folded and unfolded when you develop toggles
- Would be a decent, but not necessary option to let name elements for that case(maybe let them have name and "(Toggle)" for e.g. or w/e type it is as suffix)

**Comment by SenkyDragon** [comment]
We typically recommend organizing your VRCF components by putting them on their own empty objects, categorized by however you'd like (one each, one per category of toggle, etc).

**Comment by meriler98** [comment]
Well. Yes. But let me say e.g. I made an object "outfit toggles" and started putting them there. And the toggles consists of object toggle + blend shapes + material property and this goes for every piece. This quickly starts to occupy lots of screen space on 3rd toggle for outfit if you turn lots lf details. This is why I put a suggestion.

**Comment by SenkyDragon** [comment]
Closing this, since all vrcfury features have now been split into their own components.
