### ISSUE TITLE
[Full Controller on a prefab] Can't build: "VRCExpressionsMenu uses a parameter that is not defined"

### ISSUE THREAD

**Issue by kayla-yote** [VRCFury/VRCFury#232]
Additionally, editing the expressions menu used by the prefab has errors like "Parameter not found on the active avatar descriptor".

If I add the parameter names to Full Controller's Global Parameters, and hit Play, I can see that the generated merged Parameters and Menu lists look right, but I can't build/upload while in Play mode.

One reddit post recommended:
* Hit Play
* Copy the generated post-vrcfury avatar
* Stop Play
* Paste the generated post-vrcfury avatar
* Build/upload that copy

Is that the expected workflow?
Is this due to SDK3 or the Unity2022 update?

**Comment by SenkyDragon** [comment]
Please join the vrcfury discord at https://vrcfury.com/discord for support requests. This issue board is for verified bugs / feature requests only.
