### ISSUE TITLE
[Feature Request] Toggle gestures

### ISSUE THREAD

**Issue by imagitama** [VRCFury/VRCFury#233]
# Idea

Sometimes you want to toggle your facial expressions off but keep your fingers moving (on Quest controllers) similar to the gesture lock button on Index controllers.

# Proposed implementation

Add a global item and an option for every item in the Gestures item called "Gesture Lock" which adds a boolean "IsGesturesLocked" before playing the action for each gesture.

**Comment by fluffy-critter** [comment]
I've had requests on one of my avatars to be able to disable/lock all gestures from a single toggle, and I'm surprised that this isn't available in the VRCFury gesture controller component already. Unless I'm misunderstanding the setup for the "gesture lock" toggle, which appears to need one per gesture.

I'd expect this to be either a top-level config for the gesture object, or a thing that is available on the VRCFurry "toggle" component to disable/lock gestures (similar to how you can disable eye blinks from that same component).
