### ISSUE TITLE
[Bug] Custom menu icons compression suggestion is wrong

### ISSUE THREAD

**Issue by imagitama** [VRCFury/VRCFury#234]
# Issue

When you override a menu icon and do not enable compression, VRCFury shows an error saying your import settings are wrong.

This error is wrong - compression should be _enabled_. If you manually do it via SDK the SDK will show an error about being too large and will automatically enable compression.

# Solution

Change the error to say you need to enable compression.

Alternatively VRCFury should duplicate your custom icons and programmatically change the import settings to enable compression so no error is shown.

# Repro

1. add VRCFury component
2. add "Toggle" or "Override Menu Icon"
3. set icon to a PNG that doesnt have compression enabled
4. enter play mode
5. error shown

Doing it manually will show an error in the SDK about icon being too big

# Screenshot

![image](https://github.com/VRCFury/VRCFury/assets/1967342/787b347b-1b87-4fda-8c3f-cdcaa97a3aa5)

**Comment by SenkyDragon** [comment]
The error says it must **not** be set to none. Is this incorrect?

**Comment by imagitama** [comment]
It is incorrect. I set it to none and it still shows the error.

When you use the SDK to automatically fix the error the SDK sets compression enabled.

**Comment by SenkyDragon** [comment]
> I set it to none and it still shows the error.

The error says it must NOT be set to none. As in you must ensure that the setting is set to anything except for none. Setting it to none is the only thing you should not do.

**Comment by imagitama** [comment]
I see now. I think the error is hard to read/understand as each time I re-read it I completely ignore the "not" bit.

"and compression is enabled"

**Comment by SenkyDragon** [comment]
Reworded in eee4c8d1
