### ISSUE TITLE
[Feature Request] "Folder/Directory" prefab/object that can be used like the empty GameObject trick to group related objects, but without breaking VRCFury

### ISSUE THREAD

**Issue by chexo3** [VRCFury/VRCFury#242]
I have a lot of things on my avatar at this point, and I needed to organize them, so I heard about that trick of creating an empty GameObject and renaming it to use it as a folder, but since VRCFury assets need to be on the avatar root to be recognized, this messes things up. I think it would be handy to be able to create a VRCFury component/object/whatever that just serves to group related assets together and essentially "passes through" to the actual root.

I have no idea how feasible this is. I'm very new to Unity, I just want slightly more organized clothes.

**Comment by SenkyDragon** [comment]
This already exists in a sense. "Root-only" components can already be added to a child empty, but only if that child empty contains NO RENDERERS. This is to discourage prefab authors from using opinionated components like "bounding box fix" within their prefabs, which would mess with other things on the avatar.

**Comment by chexo3** [comment]
Oh, I see. Well, the prefabs I’m working with are avatar parts so they have renderers and so they disappear at runtime when I have them under child empties.

Is there anything that can be done about the problem of prefab authors including stuff they shouldn’t? Like, could the bounding box fix part be nuked when it’s detected?

**Comment by SenkyDragon** [comment]
What features are you hoping to use that are not available?

**Comment by chexo3** [comment]
The prefabs I’m working with are avatar parts, so they come with meshes and shaders and all that. So of course they don’t show up when I go into play mode if they’re not on the root node. It would be nice if I could use child empties to group them up, but as I understand, you don’t allow renderers on child empties because prefab authors were making broken prefabs by including stuff they shouldn’t.

What I’m wondering is if there is a compromise that can be made that would allow me to group together my prefabs in some way so I can keep them organized.

**Comment by SenkyDragon** [comment]
Which vrcfury features, specifically, are you trying to use within an empty that are not available?

**Comment by chexo3** [comment]
I don’t know, the one that makes prefabs with models show up? Like, I attach a tail prefab for instance and it’s fine on the avatar root, but with a lot of clothes and stuff I needed more organization, so I looked up how to group stuff in Unity and empties were suggested. Then you explained that renderers don’t work except on the avatar root because of prefab authors doing silly stuff? 

I’m confused because I think there is enough context here to know what I’m talking about even if I don’t exactly know what it’s called.

**Comment by SenkyDragon** [comment]
Only some limited vrcfury features are limited to the root. All of the remainder, including the most popular components like Full Controller and Toggle are available on child empties just fine, even alongside renderers. If you have a concrete example that you are not able to get working, please ask for support on the discord at https://vrcfury.com/discord
