### ISSUE TITLE
Adding any VRCFury feature breaks non-humanoid animations present in the Gesture controller

### ISSUE THREAD

**Issue by SenkyDragon** [VRCFury/VRCFury#25]
Since VRCF removes the FX mask, it has the potential to break any non-humanoid transform animations that exist in the avatar's Gesture controller. Even though these animations should probably be in FX instead, we should strive to not ever break anything already working on the base avatar.

**Comment by KrazenLabs** [comment]
I added a pull request for a quick and dirty change that at least alleviates the issue for me. Not sure if it is a reasonable change to make as only you can probably evaluate that :)

**Comment by SenkyDragon** [comment]
Should be fixed in d134616b2506c34405e1fcc4f485f58dab0f6181
