### ISSUE TITLE
[Feature request] Add advanced settings for SPS Plug Auto-Rig option 

### ISSUE THREAD

**Issue by BriteNightCloud** [VRCFury/VRCFury#254]
So, theres an Auto-Rig option that automatically adds phys bones to the plug, but what should i do if i want to configure those phys bone in some case? 
For example, at least how do i disable Grabbale and Posing or change phisics of the plug (pull, spring, etc.)?
There's no advanced settings for it, so i think it would be really useful to add some advanced settings for created phys bones.

Below listed some code i found that should be edited in case to add those advanced settings:

[com.vrcfury.vrcfury/Editor/VF/Builder/Haptics/SpsAutoRigger.cs](https://github.com/VRCFury/VRCFury/tree/main/com.vrcfury.vrcfury/Editor/VF/Builder/Haptics/SpsAutoRigger.cs) (line 64)
```
if (!bonesAlreadyExist) {
    var physbone = skin.owner().AddComponent<VRCPhysBone>();
    physbone.integrationType = VRCPhysBoneBase.IntegrationType.Advanced;
    physbone.pull = 0.8f;
    physbone.spring = 0.1f;
    physbone.stiffness = 0.3f;
    physbone.rootTransform = bones.First();

    var radiusEnd = Mathf.Max(0.0f, 1.0f - localRadius / localLength);
    physbone.radiusCurve = AnimationCurve.Linear(radiusEnd, 1.0f, 1.0f, 0.0f);
    physbone.radius = localRadius;
}
```
[com.vrcfury.vrcfury/Editor/VF/Inspector/VRCFuryHapticPlugEditor.cs](https://github.com/VRCFury/VRCFury/tree/main/com.vrcfury.vrcfury/Editor/VF/Inspector/VRCFuryHapticPlugEditor.cs) (line 109)
```
container.Add(VRCFuryEditorUtils.RefreshOnChange(() => {
    var c = new VisualElement();
    if (enableSps.boolValue) {
        var spsBox = VRCFuryEditorUtils.Section("Deformation (Super Plug Shader)", "This plug will deform toward SPS/TPS/DPS sockets\nCheck out vrcfury.com/sps for details");
        c.Add(spsBox);
        spsBox.Add(VRCFuryEditorUtils.BetterProp(
            serializedObject.FindProperty("spsAutorig"),
            "Auto-Rig (If mesh is static, add bones and a physbone to make it sway)"
        ));
```

[com.vrcfury.vrcfury/Runtime/VF/Component/VRCFuryHapticPlug.cs](https://github.com/VRCFury/VRCFury/tree/main/com.vrcfury.vrcfury/Runtime/VF/Component/VRCFuryHapticPlug.cs) (line 23)
```
public bool spsAutorig = true;
```

**Comment by SenkyDragon** [comment]
It's unlikely that we'll make this change. It's been often requested, but there's a slippery slope of how much we would support -- if we add posing options, people will ask for rigidity, and contacts, etc etc. Additionally, allowing further customization of these physbone options will be a blocker for us from changing the autorig "defaults" in the future.

Ultimately, having no configuration at all is what we settled on, and if you want more control, you should rig the mesh so you have full control over the bone layout, physbones, etc.
