### ISSUE TITLE
An option to replace action layer instead of merging it

### ISSUE THREAD

**Issue by jerryzmtz** [VRCFury/VRCFury#256]
When I try to merge an customized action layer to an avatar wih no action layer, what I expect is to "replace" avatar's action layer with my customized layer. However, what it does now is to merge my action layer with VRC default action layer: 
![image](https://github.com/VRCFury/VRCFury/assets/26083118/3e6ef0c7-edd0-48fc-a5b2-27a2c9d05080)

I reuse the same action layer for emote changing, and this include menu and parameters. So I hope full controller could support mode changing between "merge" and "replace".

**Comment by SenkyDragon** [comment]
If you want to replace your action controller completely, you should click on the action controller in your avatar descriptor so it says "None" rather than Default. For other support inquiries, please ask on the VRCFury discord at https://vrcfury.com/discord .

**Comment by SenkyDragon** [comment]
The latest release will now automatically do this for you if your base menu doesn't reference VRCEmote at all.
