### ISSUE TITLE
[Feature Request] Support for Unity multi-object editing

### ISSUE THREAD

**Issue by SophiaH67** [VRCFury/VRCFury#259]
At the moment, if you select multiple objects with similar or the same vrcfury components, it shows the following in the inspector components:

![image](https://github.com/VRCFury/VRCFury/assets/10786212/c68e16e3-814e-4673-98cb-7fbf512f49d5)

For lots of avatars with similar or the same toggles it would be really nice to support Unity's multi-object editing feature!

**Comment by SenkyDragon** [comment]
Because of the way component merging works in unity, this is basically not ever going to happen. I'd suggest taking advantage of prefabs where possible so that you can share components between avatars without having to make identical separate copies.
