### ISSUE TITLE
Toggle generated menu makes Av3Emulator menu render fails

### ISSUE THREAD

**Issue by MoePus** [VRCFury/VRCFury#26]
https://github.com/VRCFury/VRCFury/blob/0f1124ea769a8872cc562f673c303d73cf48dae6/com.vrcfury.vrcfury/Editor/VF/Builder/Manager/MenuManager.cs#L276

https://github.com/VRCFury/VRCFury/blob/0f1124ea769a8872cc562f673c303d73cf48dae6/com.vrcfury.vrcfury/Editor/VF/Builder/Manager/MenuManager.cs#L32

Makes Av3Emulator menu render fails
https://github.com/lyuma/Av3Emulator/blob/ea6e39922b5891167cb50aca78315c577b5e79a4/Editor/LyumaAv3MenuEditor.cs#L105
when accessing control.subParameters which is null.

Vrc generated menu's subParameters is not null, so i post the issue here.

**Comment by SenkyDragon** [comment]
Seems like an av3emulator bug to me, since it works in gesture manager and in vrchat itself. I fix it anyways.
