### ISSUE TITLE
[Feature Request] BlendShape and Direct Tree Optimizer standalone tools

### ISSUE THREAD

**Issue by Vavassor** [VRCFury/VRCFury#267]
I'm adapting avatars for use as NPCs in VRChat worlds. VRCFury has a few options that could be relevant to world creators editing animated characters. But because it only applies on build & upload, there's no way for me to intentionally destructively apply changes so that I can export the avatar to a world project.

Blendshape, Direct Tree Optimizer, and MMD Compatibility are some tools I was thinking of. Others that could be helpful are possibly Blink and Breathing Controllers. However, these might be challenging because the world SDK (as of 3.5.1) doesn't support state behaviors in animators.

**Comment by Amoenus** [comment]
As you specifically talk about **destructive** changes, I wonder if Building Editor Test Copy accomplishes what you ask? You can extract a prefab from the test copy and use it as an NPC in your world
