### ISSUE TITLE
Add support for specifying a prefix for VRCAnimatorPlayAudio state components inside of ``Full Controller`` components.

### ISSUE THREAD

**Issue by AraHaan** [VRCFury/VRCFury#271]
I informed Killer Kobold that their Vore System can be optimized a bit more by using this component, however the ``Source Path`` does not work as the VoreFX animation controller cannot safely assume that vrcfury is used on a person's avatar and people still do manual installs even for v3.0.1.

As such a part of Full Controller that allows specifying a prefix for it in this case it would have to be the prefab's name that is used when the user drags it to the root of the avatar. Without this the Animator View Controllers that gets added would be disabled which is not good at all for this new VRChat feature.

The Vore System here is a perfect example of the need for this, but I can see where other prefabs could also use such a feature. And yes I decided to experiment with it and noticed this problem with VRCFury.

**Comment by AraHaan** [comment]
It seems that when the component gets copied in vrcfury that it wipes out the setting for ``Source Path`` in it resulting in a disabled ``VRCAnimatorPlayAudio`` and also it wipes out say if you wanted to have the default volume and and other settings except last one to never apply it would return back to the default setting for it. I discovered it from the Av3 manager as well. As such I think some additional changes would need to be made to support it as well.

**Comment by SenkyDragon** [comment]
Fixed in https://github.com/VRCFury/VRCFury/commit/dcca243ce2fad9602ba76808839236db71ee408c
