### ISSUE TITLE
Fails to find Hips bones even-though it's here

### ISSUE THREAD

**Issue by blackorbit1** [VRCFury/VRCFury#272]
Hello,

After renaming Hoodie bones from `Hips` to `Hoodie Hips`, VRCFury can't build anymore saying that it can't find the Hips bone, even-though the avatar Hips bone is still there (see screenshot) :
![image](https://github.com/VRCFury/VRCFury/assets/38140797/354ffe34-c599-467f-86dc-5cff164bc711)

--------------
Edit:
So it looks like the problem wasn't from renaming the Hoodie armature but from putting `Armature` under `------ AVATAR BODY ------`
It would be cool if that kind of avatar organization could be supported though.

Wish you the best

**Comment by SenkyDragon** [comment]
This isn't a VRCFury issue. Within your rig definition file, unity stores your armature using static string paths, not pointers to specific objects. You cannot move or rename parts of your avatar rig without breaking the rig definition.
