### ISSUE TITLE
[Feature] Add a new "Apply In Editor" Component that can do the same as "Apply On Upload" but for editor cases when in PC or Quest Configurations.

### ISSUE THREAD

**Issue by AraHaan** [VRCFury/VRCFury#274]
It would be nice if a version of ``Apply On Upload`` could be used to "swap" on editor build configuration changes so that way the following can take affect.

- When needing to update the avatar's "thumbnail" but use ``Apply On Upload`` to swap the Quest material out with the PC one when the PC build is the active configuration.
- When you have the Mesh start out with ``None`` for Material and use ``Apply On Upload`` to swap that out with the real material for both PC and Quest builds.
- The fact that there are cases where an ``Apply In Editor`` component would probably be saner to use if it existed in VRCFury today.
  - Also the fact that it is possible to write unity editor code that can check for things like this that gets loaded upon build configuration change. It would also help with avoiding having separate copies of an avatar project on PC and Quest because adding this to VRCFury could help make the things that need to be swapped to be swapped ***before*** the VRCSDK can check and say :x: on your PC Materials that cannot be used on Quest configuration.

This was one of a few ideas I had recently on VRCFury and something I feel a lot of people would use. Who knows it might remove *most of* the use cases for ``Apply On Upload`` except for object "Turn on/Turn off".

**Comment by SenkyDragon** [comment]
I don't think this will happen in the near future. I will defer to https://github.com/kurotu/VRCQuestTools which is already quite good at resolving these issues.
