### ISSUE TITLE
Really confused and stumped.

### ISSUE THREAD

**Issue by jpisthebest** [VRCFury/VRCFury#275]
<img width="524" alt="Screenshot 2024-04-11 at 2 20 03 PM" src="https://github.com/VRCFury/VRCFury/assets/30219731/de75cfe6-665b-47fd-9555-8deb42513a1a">

Started work on an avatar, tried to upload it/test it and it's just giving me this? I'm using SDK 3.5.2 so i'm confused as heck.
Pleassee, any help would be appreciated.

**Comment by JustBuddy** [comment]
Heard this issue occurs when you install the SDK manually (outside of VCC).
They seemingly forgot to update the version number in package.json there.
Either using the VCC version directly or just changing the version in your package.json to 3.5.2 should resolve this.
