### ISSUE TITLE
vcc.vrcfury.com returns 500 if there is `If-None-Match` header.

### ISSUE THREAD

**Issue by anatawa12** [VRCFury/VRCFury#277]
In previous https://vcc.vrcfury.com/, the server returned `Etag` header.

In my vpm client, we optimize downloading repository by passing `If-None-Match` header.

However, the https://vcc.vrcfury.com/ now returns `500` error ([Cloudflare Error 1101: Rendering error](https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-1xxx-errors/#error-1101-rendering-error))

```bash
curl -v -H "If-None-Match: W/\"cdcfa3839c33f8736fda55ca006056e2218084e7fdced129e406d322e7a87304\"" 'https://vcc.vrcfury.com/'
```

**Comment by SenkyDragon** [comment]
Fixed the underlying error. ETag still isn't supported, as the vcc listing is now dynamically generated using a cloudflare worker and reimplementing ETags in the worker isn't something I really have the time to do right now.

**Comment by anatawa12** [comment]
I think not implementing Etag is fine. Thank you
