### ISSUE TITLE
[Bug] Copying object toggles to new avatars no longer works.

### ISSUE THREAD

**Issue by SuikaNishi** [VRCFury/VRCFury#292]
I'm currently using version 1.947 and use the VCC to maintain/update VRCFury.

I typically use a base avatar prefab that I've created for my avatar and then duplicate it in the same scene in Unity to put on new outfits.  Most of my toggles are fairly standard between each avatar/outfit, so I generally put the VRCFury Toggle components on an empty game object and then just copy that game object to each new avatar to then customize the toggles for that outfit. This has worked flawlessly for a long time, but now it seems that when I do this, some of the toggle components fail to load properly and just show as "VRC Fury (Script)" in the inspector.

After checking the console, it seems that the components are failing because the object toggles are calling to objects that are not children of the new avatar that I copied the game object to.  I used to be able to just drag the new objects to be toggled from the new avatar into the toggle components, however I am no longer able to do this.  I'm not sure which version started having this issue, but it would definitely have been after 1.940.

Here is one of the errors from the editor console:

Exception: Sakurinra Base (Vivid Eve)/VividEve_Shinra_Black/ArmAcc is not a child of Sakurinra Base (Vague)
VF.Builder.VFGameObject.GetPath (VF.Builder.VFGameObject root, System.Boolean prettyRoot) (at ./Packages/com.vrcfury.vrcfury/Editor/VF/Builder/VFGameObject.cs:190)
VF.Service.ActionClipService.LoadStateAdv (System.String name, VF.Model.State state, VF.Builder.VFGameObject avatarObject, VF.Builder.VFGameObject animObject, VF.Service.ActionClipService service) (at ./Packages/com.vrcfury.vrcfury/Editor/VF/Service/ActionClipService.cs:225)
VF.Inspector.VRCFuryActionDrawer+<>c__DisplayClass1_0.<Render>g__UpdateDebug|2 () (at ./Packages/com.vrcfury.vrcfury/Editor/VF/Inspector/VRCFuryActionEditor.cs:98)
VF.Inspector.VRCFuryActionDrawer.Render (UnityEditor.SerializedProperty prop) (at ./Packages/com.vrcfury.vrcfury/Editor/VF/Inspector/VRCFuryActionEditor.cs:109)
VF.Inspector.VRCFuryActionDrawer.CreatePropertyGUI (UnityEditor.SerializedProperty prop) (at ./Packages/com.vrcfury.vrcfury/Editor/VF/Inspector/VRCFuryActionEditor.cs:29)
UnityEditor.UIElements.PropertyField.Reset (UnityEditor.SerializedProperty newProperty) (at <80a8ce1980c648dca8e68f0d8aa3b930>:0)
UnityEditor.UIElements.PropertyField.Reset (UnityEditor.UIElements.SerializedPropertyBindEvent evt) (at <80a8ce1980c648dca8e68f0d8aa3b930>:0)
UnityEditor.UIElements.PropertyField.ExecuteDefaultActionAtTarget (UnityEngine.UIElements.EventBase evt) (at <80a8ce1980c648dca8e68f0d8aa3b930>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <332857d8803a4878904bcf8f9581ec33>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtCurrentTargetAndPh

**Comment by SenkyDragon** [comment]
Fixed in 1.948
