### ISSUE TITLE
[BUG] Unlimited Parameters Breaks Syncing Between PC and Quest Avatars with Different Menu Layouts

### ISSUE THREAD

**Issue by WhatInTheChap** [VRCFury/VRCFury#296]
Unlimited Parameters cause syncing issues between PC and Quest avatars with different menu layouts. This occurs because Unlimited Parameters syncs in the order they appear in the menu. Instead, it should sync parameters found in the menu in the order they appear in the avatar's parameters.

Implementing this change would allow Unlimited Parameters to function as a drop-in upgrade for existing avatars, ensuring only parameters present in the menu are synced. Additionally, this approach simplifies debugging for avatar creators, as reordering an avatar's parameters is generally easier than reordering an avatar's controls/menus.

**Comment by SenkyDragon** [comment]
While the order /probably/ shouldn't be based on the order in the menu, it's kinda irrelevant since the presence in the menu will still be important. If you are changing the layout of your quest menu, then contained items are also probably different, which will still break the unlimited parameters sync.

This is already documented on the VRCF quest page:
https://vrcfury.com/tutorials/quest/
> If you are using VRCFury's `Unlimited Parameters` component, you also need to make sure that your Menu matches between the two versions, otherwise it may optimize different parameters between the two platforms.

**Comment by WhatInTheChap** [comment]
I reported a bug where Unlimited Parameters causes syncing issues on PC-Quest compatible avatars with different menu layouts. The only solution I could find is to redesign the avatar's menus, which is destructive, messy, and contradicts the promises on the VRCF home page:

> No more layers, no more menu editing

> Your existing layers, parameters, and menus will be untouched, and VRCFury will keep its work totally separate from yours.

My example fix would slightly improve upon the current system, though I'd recommend finding a better solution.

**Comment by Toys0125** [comment]
I also commented on the Unlimted Parameters not working based on the parameters list because I tend to limit what's on my quest avatars, which only have some menu options on PC for quest users except what they can see and use.

**Comment by SenkyDragon** [comment]
VRCF currently does not support syncing between Quest / Desktop avatars with different descriptor params, menus, or vrcfury components. I'm linking this issue to https://github.com/VRCFury/VRCFury/issues/302 which intends to somewhat resolve this issue in a more generic way.
