### ISSUE TITLE
[VRCF Toggle component] Better support for slider settings

### ISSUE THREAD

**Issue by Martin-H2** [VRCFury/VRCFury#299]
![image](https://github.com/VRCFury/VRCFury/assets/6370147/3af71f8e-2af6-4e00-84a3-68f583be270b)

In the slider settings it is only possible to define the max value of the slider, but it is in many cases crucial to define the lower limit, instead of using the value currently set in the unity scene. 

e.g.: imagine you are creating scale slider or shader properties, you usually have the "middle ground" value set in unity as default.
Or in the case of the screenshot: min brightness. You can set the max value of the slider, but to set the min value you have to mess up your material in your unity scene. Now you don't have the impression how bright your avatar "usually" is, but the lowers edge case.

Also I would recommend to create an own component instead of using the VRCF Toggle component. Actually one for every data-type would be perfect:
- VRCF Toggle component -> boolean
- VRCF Switch component -> int
- VRCF Slider component -> float

**Comment by SenkyDragon** [comment]
"Minimum values" can already be effectively set by using a VRCFury | Apply During Upload component. For support requests and general inquiries, please use our support discord at https://vrcfury.com/discord -- this issue board is for confirmed bugs and feature requests only.

**Comment by Martin-H2** [comment]
well it was a feature request, because current solution is complicated :)
thats why issue tracker

**Comment by SenkyDragon** [comment]
The latest release has better wording to reflect this in the component.
