### ISSUE TITLE
New VRCFury Component for "Set as Body"

### ISSUE THREAD

**Issue by SenkyDragon** [VRCFury/VRCFury#315]
Basically a version of armature link that always just moves the object to the avatar root and calls it Body. Useful for some weird cases involving MMD where the MMD-controlled mesh can be swapped out.

**Comment by Voxian** [comment]
I would like to recommend making a generic tool for this situation. There are some situations where I want to simply move an object from one packed hierarchy to another area without changing it's name. This is mostly only relevant when stations play animations on the avatar, but could also be useful for other situations as well.

**Comment by SenkyDragon** [comment]
> This is mostly only relevant when stations play animations on the avatar, but could also be useful for other situations as well.

Have you seen world stations that control a mesh other than Body? MMD is already quite rare, anything else is probably even more unusual.
