### ISSUE TITLE
Object Toggle doesn't accept objects outside prefab

### ISSUE THREAD

**Issue by porkyoot** [VRCFury/VRCFury#40]
As explained in Discord, there is a bug that prevents object from outside the prefab to be used in Object toggles.

Here's a video of the issue posted in Discord.
https://cdn.discordapp.com/attachments/1001424777401077830/1124823066334199859/2023-07-01_23-38-04_.mkv

**Comment by SenkyDragon** [comment]
This is unfortunately just a limitation in the way unity works. Prefabs cannot contain references to object IDs that are outside of the saved file. The only real alternative here is to use an animation clip that toggles the body mesh (and vrcf will automatically locate the proper point in the hierarchy, allowing the clip to target the Body even though it's outside the prefab).
