### ISSUE TITLE
Animator Controller Overrides

### ISSUE THREAD

**Issue by Hacksawfred3232** [VRCFury/VRCFury#5]
Before that question gets asked - No, this is not a SDK 2 backwards compat request or simliar there of. This is mostly a request to reduce the workload when working with multiple instances of the same avatar or its base. This also kinda helps with projects that are managed with a SVC system like Gitea. 

Allowing VRCFury to detect whenever a override controller was supplied and then "override" the animation clips used in the final animation controller, should in turn will allow the end user to replace animation clips per avatar instance without having to navigate the animation state machine for a specific clip to replace. This reduces the work time and complexity by allowing a single master copy of a working animator controller to exist and then allow replacements of certian animations without the need of copying and/or modifying said master copy. This allows easier implementation of certain customization options, like for example in GoLoco:
https://www.craft.do/s/CxY701Ne9Ng5Ev/b/81EE8C20-F01E-49E5-B64C-61B54F428D7F/Change-the-turntable-animation
While other changes would require modification of the base controller itself, there are other animation systems that would benefit.

Only problem is, I wouldn't know how to go about making such a patch. A casual glance through unity documentation and the current codebase doesn't show an easy way to implement this. Ideally, this should be implemented when VRCFury registers what controllers are used for the "Full Controller" feature. Any ideas are welcome.

**Comment by SenkyDragon** [comment]
I don't think the user experience for this sort of override works very well, since it requires unpacking and changing the full override controller, and modifying source files is typically the opposite of what we're trying to encourage.

However, since it should /probably/ work anyways, I implemented it just for fun in 903edb61.
