### ISSUE TITLE
Write Defaults Fix is improperly storing defaults for merged WD off states

### ISSUE THREAD

**Issue by AtriusX** [VRCFury/VRCFury#50]
Ran into this issue when trying to fragment my avatar's FX controller so I could work with it more easily. It works well but unfortunately since it adds a base layer and my controllers use WD Off it was breaking some of my animations. From what I can tell there's no way to force it to skip this step, though I was able to work around the issue by commenting out `AddBuilder(new FixWriteDefaultsBuilder(), avatarObject);` in `VRCFuryBuilder.cs`

**Comment by SenkyDragon** [comment]
Can you give details about specifically what the problem is? FixWriteDefaultsBuilder only adds properties to the base layer if they are actually used by vrcfury's own added animations, so it shouldn't be possible for it to affect your animations unless you are animating the same things.

**Comment by AtriusX** [comment]
Sure, basically what I've been trying to do is split my controller up into smaller animator ones using the Full Controller feature. I have the main controller currently and a smaller one that I append for a weapons system. My avatar uses write defaults off to allow for a bit more complexity in what I can do with it. What's happening is that when the full controller appends the other controller to the main one, it adds another layer over top which provides a default state animation.

![image](https://github.com/VRCFury/VRCFury/assets/7331441/87576189-9fb4-40e0-aa14-cfbac76e6247)

While the feature does not update the WD states for any animation it copies to the controller, having that default layer effectively emulates WD On and breaks how some of my animations behave as a result. As far as I'm aware there isn't anything that currently allows me to disable this behavior with the Full Controller feature.

**Comment by SenkyDragon** [comment]
I believe this is actually a bug. VRCF is only supposed to add properties to the clip in the Defaults layer if it originally came from a state that had WD on. It does this as a part of the process to "convert" WD on layers to WD off layers. However, I think that logic may have been lost at some point.
