### ISSUE TITLE
Add support for shader UV toggles

### ISSUE THREAD

**Issue by Inverness** [VRCFury/VRCFury#6]
I use the ACLS Shader and its support for the inventory system (pioneered by SCSS) to implement toggles. This involves using specific shader parameters to toggle parts of a mesh based on their UV's.

I would like the ability to generate toggles for this directly, rather than having to create an animation clip manually.

Both ACLS and SCSS provide the following shader parameters for these toggles:
```
		[ToggleUI]_InventoryItem01Animated("Toggle Item 1", Float) = 1.0
		[ToggleUI]_InventoryItem02Animated("Toggle Item 2", Float) = 1.0
		[ToggleUI]_InventoryItem03Animated("Toggle Item 3", Float) = 1.0
		[ToggleUI]_InventoryItem04Animated("Toggle Item 4", Float) = 1.0
		[ToggleUI]_InventoryItem05Animated("Toggle Item 5", Float) = 1.0
		[ToggleUI]_InventoryItem06Animated("Toggle Item 6", Float) = 1.0
		[ToggleUI]_InventoryItem07Animated("Toggle Item 7", Float) = 1.0
		[ToggleUI]_InventoryItem08Animated("Toggle Item 8", Float) = 1.0
		[ToggleUI]_InventoryItem09Animated("Toggle Item 9", Float) = 1.0
		[ToggleUI]_InventoryItem10Animated("Toggle Item 10", Float) = 1.0
		[ToggleUI]_InventoryItem11Animated("Toggle Item 11", Float) = 1.0
		[ToggleUI]_InventoryItem12Animated("Toggle Item 12", Float) = 1.0
		[ToggleUI]_InventoryItem13Animated("Toggle Item 13", Float) = 1.0
		[ToggleUI]_InventoryItem14Animated("Toggle Item 14", Float) = 1.0
		[ToggleUI]_InventoryItem15Animated("Toggle Item 15", Float) = 1.0
		[ToggleUI]_InventoryItem16Animated("Toggle Item 16", Float) = 1.0
```
For ACLS and SCSS, the toggle is visible when the value is 1, and hidden when it is 0.

I also know that Poiyomi implements the same feature but called UV Tile Discard, however I don't know what parameter names it uses or if 1 and 0 have the same meaning.

**Comment by PhoxVRC** [comment]
I was going to write, its similar to [Poiyomi's Tile Discard](https://www.poiyomi.com/special-fx/uv-tile-discard). Its more optimised for toggling meshes.
