### ISSUE TITLE
Strange issue with continuous bone stretching

### ISSUE THREAD

**Issue by AtriusX** [VRCFury/VRCFury#60]
I've begun to notice an issue occurring with some of the bones on my avatar continuously stretching while running with the avatar emulator. I'm not sure as to what conditions are causing this behavior to occur currently, but at least from testing I know the issue appears to start in version `1.257` and up. The behavior occurs even when no features are included in the component, and doesn't occur when VRCFury is not set to build in play mode.

[Here's an example of what is occurring on my end.](https://github.com/VRCFury/VRCFury/assets/7331441/c1dd66be-884a-45db-9b12-723bf6e9b30e) I apologize I can't readily provide more information.

**Comment by SenkyDragon** [comment]
Give 1.268 a shot, since we just made fx transform masks even more restrictive

**Comment by AtriusX** [comment]
Issue appears to have been resolved in that version; I don't see the bones stretching anymore. Thanks!
