### ISSUE TITLE
Armature link doesn't apply if force object state is higher in list

### ISSUE THREAD

**Issue by ItsLynix** [VRCFury/VRCFury#79]
In certain situations, it seems VRCFury doesn't correctly link assets after exported into VRChat, while it works fine in unity

In following setup, object "tophat" does not correctly linked and the toggle to turn it does not work in vrchat, but everything seems to work fine in unity
![image](https://github.com/VRCFury/VRCFury/assets/71310187/cb85c02f-325d-4c6d-ad0c-bee25618dd76)

In following setup, everything works as expected
![image](https://github.com/VRCFury/VRCFury/assets/71310187/db690b9b-16a6-4609-8d98-470497fc3faa)

**Comment by SenkyDragon** [comment]
What version of VRCFury? Can you try it with the latest release? The order of Force Object State in relation to any other feature has been irrelevant for quite a long time now. Is it possible you're on a very old version?

**Comment by ItsLynix** [comment]
> What version of VRCFury? Can you try it with the latest release? The order of Force Object State in relation to any other feature has been irrelevant for quite a long time now. Is it possible you're on a very old version?

I can't seem to be able to check the version, given there's no menu for it from what I can see in Tools, but I downloaded and used the VRCFury installer on august 3rd, so I figure it would've gotten the latest version at that time?

**Comment by ItsLynix** [comment]
I did just run another update from inside unity, not using the installer itself, and it seems the issue is fixed, sorry for wasting your time, I admire your work!
