### ISSUE TITLE
Avatar remains stuck in T-pose when using AV3 Emulator in all versions after 1.394.0

### ISSUE THREAD

**Issue by AtriusX** [VRCFury/VRCFury#97]
Me and a few other people have noticed recently some issues popping up with the emulator following updates to the latest version of the tool. The issue appears to only occur in all versions of VRCFury from 1.395.0 to 1.401.0 (current as of this ticket). In these versions the emulator appears to cease functioning entirely, and the avatar remains stuck in a T-pose.

The issue only appears when using AV3Emulator; GestureManager does not appear to be affected.

**Comment by Toys0125** [comment]
I have not experienced this behavior. Granted, I use GestureManager and AV3Emulator together since there are no issues with both being in the same project.

**Comment by AtriusX** [comment]
It appears I forgot to close this issue; the behavior stopped occurring after a certain update so this issue has been resolved.
